#ifndef VERSION_HPP
#define VERSION_HPP

#define OSRM_VERSION_MAJOR "4"
#define OSRM_VERSION_MINOR "9"
#define OSRM_VERSION_PATCH "0"

#define OSRM_VERSION "v" OSRM_VERSION_MAJOR "." OSRM_VERSION_MINOR "." OSRM_VERSION_PATCH

#endif // VERSION_HPP
